openapi: 3.0.3
info:
  title: Projeto de Controle de Bebidas - SENAI Jandira
  description: |-
   API destinada para controle de bebidas
  termsOfService: http://swagger.io/terms/
  contact:
    email: kayquebrennoferreira@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://
paths:
  /v1/delicia-gelada/admin/usuario:
    post:
      tags:
        - (Admin) Usuário
      security:
        - bearerAuth: []
      
      summary: Adiciona um novo Usuario
      description: Adiciona um novo Usuario
      requestBody:
        description: JSON contendo os dados do novo USUARIO a ser inserido no sistema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      responses:
        '201':
          description: Success Created Item
        '400':
          description: Error Bad Request
        '409':
          description: Error Conflict
        '415':
          description: Error Content Type
        '500':
          description: Error Internal Server (Controller | Model)
    get:
      tags:
        - (Admin) Usuário
      security:
        - bearerAuth: []
      summary: Lista todos os Usuarios
      description: Listagem de todos os USUARIOS registrados no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UsuarioGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/admin/usuario/:{id}:
    get:
      tags:
        - (Admin) Usuário
      security:
        - bearerAuth: []
      summary: Busca um Usuário pelo ID
      description: Retorna um Usuário pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca do Usuário
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsuarioGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)
    put:
      tags:
        - (Admin) Usuário
      security:
        - bearerAuth: []
      summary: Atualiza um usuario pelo ID
      description: Atualiza um usuário pelo ID colocando as informações da mesma forma que o POST
      parameters:
        - name: id
          in: path
          description: ID para atualizar o Usuário
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Dados para atualizar um usuário existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      responses:
        '200':
          description: Ok
        '400':
          description: Error Bad Request (id | dados)
        '404':
          description: Error Not Found
        '409':
          description: Error Conflict
        '415':
          description: Error Content Type
        '500':
          description: Error internal server (Controller | Model)    
    delete:
      tags:
        - (Admin) Usuário
      security:
        - bearerAuth: []
      summary: Exclui um Usuário pelo ID
      description: Excluir um Usuário existente buscando pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca do usuário
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Success Delete
        '400':
          description: Error Bad Request (ID)
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/admin/usuario/login:
    post:
      tags:
        - (Admin) Usuário
      summary: Fazer login com informações registradas no sistema
      description: Fazer login
      requestBody:
        description: JSON contendo os dados do login do usuário
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsuarioLogin'
        required: true
      responses:
        '201':
          description: Ok
        '400':
          description: Error Bad Request
        '401':
          description: Error Unauthorized
        '415':
          description: Error Content Type
        '500':
          description: Error Internal Server (Controller | Model)
  
  /v1/delicia-gelada/admin/bebida:
    post:
      tags:
        - (Admin) Bebida
      security:
        - bearerAuth: []
      summary: Adiciona uma nova Bebida
      description: Adiciona uma nova Bebida
      requestBody:
        description: JSON contendo os dados da nova BEBIDA a ser inserida no sistema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bebida'
        required: true
      responses:
        '201':
          description: Success Created Item ou Success Created Item Warning
        '400':
          description: Error Bad Request
        '415':
          description: Error Content Type
        '500':
          description: Error Internal Server (Controller | Model)
    get:
      tags:
        - (Admin) Bebida
      summary: Lista todas as Bebidas
      description: Listagem de todas as BEBIDAS registrados no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BebidaGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/admin/bebida/:{id}:
    get:
      tags:
        - (Admin) Bebida
      summary: Busca uma Bebida pelo ID
      description: Retorna uma Bebida pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da Bebida
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BebidaGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)
    put:
      tags:
        - (Admin) Bebida
      security:
        - bearerAuth: []
      summary: Atualiza uma bebida pelo ID
      description: Atualiza uma bebida pelo ID colocando as informações da mesma forma que o POST
      parameters:
        - name: id
          in: path
          description: ID para atualizar a bebida
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Dados para atualizar uma bebida existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bebida'
        required: true
      responses:
        '200':
          description: Ok
        '400':
          description: Error Bad Request (id | dados)
        '404':
          description: Error Not Found
        '415':
          description: Error Content Type
        '500':
          description: Error internal server (Controller | Model)    
    delete:
      tags:
        - (Admin) Bebida
      security:
        - bearerAuth: []
      summary: Exclui uma Bebida pelo ID
      description: Excluir uma Bebida existente buscando pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da bebida
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Success Delete
        '400':
          description: Error Bad Request (ID)
        '500':
          description: Error Internal Server (Controller | Model)
  
  /v1/delicia-gelada/admin/categoria:
    post:
      tags:
        - (Admin) Categoria
      security:
        - bearerAuth: []
      summary: Adiciona uma nova Categoria
      description: Adiciona uma nova Categoria
      requestBody:
        description: JSON contendo os dados da nova CATEGORIA a ser inserida no sistema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Categoria'
        required: true
      responses:
        '201':
          description: Success Created Item
        '400':
          description: Error Bad Request
        '415':
          description: Error Content Type
        '500':
          description: Error Internal Server (Controller | Model)
    get:
      tags:
        - (Admin) Categoria
      summary: Lista todas as Categorias
      description: Listagem de todas as CATEGORIAS registrados no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoriaGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/admin/categoria/:{id}:
    get:
      tags:
        - (Admin) Categoria
      summary: Busca uma Categoria pelo ID
      description: Retorna uma Categoria pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da Categoria
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriaGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)
    put:
      tags:
        - (Admin) Categoria
      security:
        - bearerAuth: []
      summary: Atualiza uma categoria pelo ID
      description: Atualiza uma categoria pelo ID colocando as informações da mesma forma que o POST
      parameters:
        - name: id
          in: path
          description: ID para atualizar a Categoria
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Dados para atualizar uma Categoria existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Categoria'
        required: true
      responses:
        '200':
          description: Ok
        '400':
          description: Error Bad Request (id | dados)
        '404':
          description: Error Not Found
        '415':
          description: Error Content Type
        '500':
          description: Error internal server (Controller | Model)    
    delete:
      tags:
        - (Admin) Categoria
      security:
        - bearerAuth: []
      summary: Exclui uma Categoria pelo ID
      description: Excluir uma Categoria existente buscando pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da categoria
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Success Delete
        '400':
          description: Error Bad Request (ID)
        '500':
          description: Error Internal Server (Controller | Model)
  
  /v1/delicia-gelada/admin/marca:
    post:
      tags:
        - (Admin) Marca
      security:
        - bearerAuth: []
      summary: Adiciona uma nova Marca
      description: Adiciona uma nova Marca
      requestBody:
        description: JSON contendo os dados da nova MARCA a ser inserida no sistema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Marca'
        required: true
      responses:
        '201':
          description: Success Created Item
        '400':
          description: Error Bad Request
        '415':
          description: Error Content Type
        '500':
          description: Error Internal Server (Controller | Model)
    get:
      tags:
        - (Admin) Marca
      summary: Lista todas as Marcas
      description: Listagem de todas as MARCAS registrados no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MarcaGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/admin/marca/:{id}:
    get:
      tags:
        - (Admin) Marca
      summary: Busca uma Marca pelo ID
      description: Retorna uma Marca pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da Marca
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarcaGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)
    put:
      tags:
        - (Admin) Marca
      security:
        - bearerAuth: []
      summary: Atualiza uma marca pelo ID
      description: Atualiza uma marca pelo ID colocando as informações da mesma forma que o POST
      parameters:
        - name: id
          in: path
          description: ID para atualizar a Marca
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Dados para atualizar uma Marca existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Marca'
        required: true
      responses:
        '200':
          description: Ok
        '400':
          description: Error Bad Request (ID | Dados)
        '404':
          description: Error Not Found
        '415':
          description: Error Content Type
        '500':
          description: Error internal server (Controller | Model)    
    delete:
      tags:
        - (Admin) Marca
      security:
        - bearerAuth: []
      summary: Exclui uma Marca pelo ID
      description: Excluir uma Marca existente buscando pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da marca
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Success Delete
        '400':
          description: Error Bad Request (ID)
        '500':
          description: Error Internal Server (Controller | Model)
  
  /v1/delicia-gelada/admin/sabor:
    post:
      tags:
        - (Admin) Sabor
      security:
        - bearerAuth: []
      summary: Adiciona um novo Sabor
      description: Adiciona um novo Sabor
      requestBody:
        description: JSON contendo os dados do novo SABOR a ser inserido no sistema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sabor'
        required: true
      responses:
        '201':
          description: Success Created Item
        '400':
          description: Error Bad Request
        '415':
          description: Error Content Type
        '500':
          description: Error Internal Server (Controller | Model)
    get:
      tags:
        - (Admin) Sabor
      summary: Lista todos os Sabores
      description: Listagem de todos os Sabores registrados no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SaborGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/admin/sabor/:{id}:
    get:
      tags:
        - (Admin) Sabor
      summary: Busca um Sabor pelo ID
      description: Retorna um Sabor pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca do Sabor
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaborGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)
    put:
      tags:
        - (Admin) Sabor
      security:
        - bearerAuth: []
      summary: Atualiza um Sabor pelo ID
      description: Atualiza um sabor pelo ID colocando as informações da mesma forma que o POST
      parameters:
        - name: id
          in: path
          description: ID para atualizar o SABOR
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Dados para atualizar um Sabor existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Sabor'
        required: true
      responses:
        '200':
          description: Ok
        '400':
          description: Error Bad Request (ID | Dados)
        '404':
          description: Error Not Found
        '415':
          description: Error Content Type
        '500':
          description: Error internal server (Controller | Model)    
    delete:
      tags:
        - (Admin) Sabor
      security:
        - bearerAuth: []
      summary: Exclui um Sabor pelo ID
      description: Excluir um sabor existente buscando pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca do Sabor
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Success Delete
        '400':
          description: Error Bad Request (ID)
        '500':
          description: Error Internal Server (Controller | Model)
  
  /v1/delicia-gelada/admin/caracteristica:
    post:
      tags:
        - (Admin) Característica
      security:
        - bearerAuth: []
      summary: Adiciona uma nova Característica
      description: Adiciona uma nova Característica
      requestBody:
        description: JSON contendo os dados da nova CARACTERÍSTICA a ser inserida no sistema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Caracteristica'
        required: true
      responses:
        '201':
          description: Success Created Item
        '400':
          description: Error Bad Request
        '415':
          description: Error Content Type
        '500':
          description: Error Internal Server (Controller | Model)
    get:
      tags:
        - (Admin) Característica
      summary: Lista todas as Características
      description: Listagem de todas as Características registradas no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaracteristicaGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/admin/caracteristica/:{id}:
    get:
      tags:
        - (Admin) Característica
      summary: Busca uma Característica pelo ID
      description: Retorna uma Característica pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da Característica
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CaracteristicaGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)
    put:
      tags:
        - (Admin) Característica
      security:
        - bearerAuth: []
      summary: Atualiza uma Característica pelo ID
      description: Atualiza uma característica pelo ID colocando as informações da mesma forma que o POST
      parameters:
        - name: id
          in: path
          description: ID para atualizar a CARACTERÍSTICA
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Dados para atualizar uma Característica existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Caracteristica'
        required: true
      responses:
        '200':
          description: Ok
        '400':
          description: Error Bad Request (ID | Dados)
        '404':
          description: Error Not Found
        '415':
          description: Error Content Type
        '500':
          description: Error internal server (Controller | Model)    
    delete:
      tags:
        - (Admin) Característica
      security:
        - bearerAuth: []
      summary: Exclui uma Característica pelo ID
      description: Excluir uma característica existente buscando pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da Característica
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Success Delete
        '400':
          description: Error Bad Request (ID)
        '500':
          description: Error Internal Server (Controller | Model)
  
  /v1/delicia-gelada/admin/tipo_embalagem:
    post:
      tags:
        - (Admin) Tipo de Embalagem
      security:
        - bearerAuth: []
      summary: Adiciona um novo Tipo de Embalagem
      description: Adiciona um novo Tipo de Embalagem
      requestBody:
        description: JSON contendo os dados do novo tipo de embalagem a ser inserida no sistema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TipoEmbalagem'
        required: true
      responses:
        '201':
          description: Success Created Item
        '400':
          description: Error Bad Request
        '415':
          description: Error Content Type
        '500':
          description: Error Internal Server (Controller | Model)
    get:
      tags:
        - (Admin) Tipo de Embalagem
      summary: Lista todos os Tipo de Embalagem
      description: Listagem de todos os Tipo de Embalagem registradas no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TipoEmbalagemGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/admin/tipo_embalagem/:{id}:
    get:
      tags:
        - (Admin) Tipo de Embalagem
      summary: Busca um Tipo de Embalagem pelo ID
      description: Retorna um Tipo de Embalagem pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca do Tipo de Embalagem
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TipoEmbalagemGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)
    put:
      tags:
        - (Admin) Tipo de Embalagem
      security:
        - bearerAuth: []
      summary: Atualiza um Tipo de Embalagem pelo ID
      description: Atualiza um tipo de embalagem pelo ID colocando as informações da mesma forma que o POST
      parameters:
        - name: id
          in: path
          description: ID para atualizar o TIPO DE EMBALAGEM
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Dados para atualizar um Tipo de Embalagem existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TipoEmbalagem'
        required: true
      responses:
        '200':
          description: Ok
        '400':
          description: Error Bad Request (ID | Dados)
        '404':
          description: Error Not Found
        '415':
          description: Error Content Type
        '500':
          description: Error internal server (Controller | Model)    
    delete:
      tags:
        - (Admin) Tipo de Embalagem
      security:
        - bearerAuth: []
      summary: Exclui um Tipo de Embalagem pelo ID
      description: Excluir um tipo de embalagem existente buscando pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca do Tipo de Embalagem
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Success Delete
        '400':
          description: Error Bad Request (ID)
        '500':
          description: Error Internal Server (Controller | Model)
  
  /v1/delicia-gelada/admin/foto:
    post:
      tags:
        - (Admin) Foto
      security:
        - bearerAuth: []
      summary: Adiciona uma nova Foto
      description: Adiciona uma nova Foto
      requestBody:
        description: JSON contendo os dados da nova Foto a ser inserida no sistema
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Foto'
        required: true
      responses:
        '201':
          description: Success Created Item
        '400':
          description: Error Bad Request
        '415':
          description: Error Content Type
        '500':
          description: Error Internal Server (Controller | Model)
    get:
      tags:
        - (Admin) Foto
      summary: Lista todas as Fotos
      description: Listagem de todas as Fotos registradas no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FotoGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/admin/foto/:{id}:
    get:
      tags:
        - (Admin) Foto
      summary: Busca uma Foto pelo ID
      description: Retorna uma Foto pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da Foto
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FotoGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)
    put:
      tags:
        - (Admin) Foto
      security:
        - bearerAuth: []
      summary: Atualiza uma Foto pelo ID
      description: Atualiza uma foto pelo ID colocando as informações da mesma forma que o POST
      parameters:
        - name: id
          in: path
          description: ID para atualizar a FOTO
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Dados para atualizar uma Foto existente
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Foto'
        required: true
      responses:
        '200':
          description: Ok
        '400':
          description: Error Bad Request (ID | Dados)
        '404':
          description: Error Not Found
        '415':
          description: Error Content Type
        '500':
          description: Error internal server (Controller | Model)    
    delete:
      tags:
        - (Admin) Foto
      security:
        - bearerAuth: []
      summary: Exclui uma Foto pelo ID
      description: Excluir uma foto existente buscando pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da Foto
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Success Delete
        '400':
          description: Error Bad Request (ID)
        '500':
          description: Error Internal Server (Controller | Model)


  ############### LANDING PAGE ###############

  /v1/delicia-gelada/bebida:
    get:
      tags:
        - (Landing-Page) Bebida
      summary: Lista todas as Bebidas
      description: Listagem de todas as BEBIDAS registrados no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BebidaGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/bebida/:{id}:
    get:
      tags:
        - (Landing-Page) Bebida
      summary: Busca uma Bebida pelo ID
      description: Retorna uma Bebida pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da Bebida
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BebidaGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)

  /v1/delicia-gelada/categoria:
    get:
      tags:
        - (Landing-Page) Categoria
      summary: Lista todas as Categorias
      description: Listagem de todas as CATEGORIAS registrados no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoriaGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/categoria/:{id}:
    get:
      tags:
        - (Landing-Page) Categoria
      summary: Busca uma Categoria pelo ID
      description: Retorna uma Categoria pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da Categoria
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriaGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)

  /v1/delicia-gelada/marca:
    get:
      tags:
        - (Landing-Page) Marca
      summary: Lista todas as Marcas
      description: Listagem de todas as MARCAS registrados no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MarcaGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/marca/:{id}:
    get:
      tags:
        - (Landing-Page) Marca
      summary: Busca uma Marca pelo ID
      description: Retorna uma Marca pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da Marca
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarcaGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)

  /v1/delicia-gelada/sabor:
    get:
      tags:
        - (Landing-Page) Sabor
      summary: Lista todos os Sabores
      description: Listagem de todos os Sabores registrados no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SaborGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/sabor/:{id}:
    get:
      tags:
        - (Landing-Page) Sabor
      summary: Busca um Sabor pelo ID
      description: Retorna um Sabor pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca do Sabor
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SaborGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)

  /v1/delicia-gelada/caracteristica:
    get:
      tags:
        - (Landing-Page) Característica
      summary: Lista todas as Características
      description: Listagem de todas as Características registradas no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaracteristicaGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/caracteristica/:{id}:
    get:
      tags:
        - (Landing-Page) Característica
      summary: Busca uma Característica pelo ID
      description: Retorna uma Característica pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da Característica
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CaracteristicaGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)

  /v1/delicia-gelada/tipo_embalagem:
    get:
      tags:
        - (Landing-Page) Tipo de Embalagem
      summary: Lista todos os Tipo de Embalagem
      description: Listagem de todos os Tipo de Embalagem registradas no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TipoEmbalagemGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/tipo_embalagem/:{id}:
    get:
      tags:
        - (Landing-Page) Tipo de Embalagem
      summary: Busca um Tipo de Embalagem pelo ID
      description: Retorna um Tipo de Embalagem pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca do Tipo de Embalagem
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TipoEmbalagemGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)

  /v1/delicia-gelada/foto:
    get:
      tags:
        - (Landing-Page) Foto
      summary: Lista todas as Fotos
      description: Listagem de todas as Fotos registradas no sistema
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FotoGet'  
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/delicia-gelada/foto/:{id}:
    get:
      tags:
        - (Landing-Page) Foto
      summary: Busca uma Foto pelo ID
      description: Retorna uma Foto pelo ID
      parameters:
        - name: id
          in: path
          description: ID para realizar a busca da Foto
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FotoGet'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)



components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Usuario:
      required:
        - nome
        - email
        - senha
      type: object
      properties:
        nome:
          type: string
          example: Admin
          description: O número máximo de caracteres é de 30
          minLength: 4
          maxLength: 30
        email:
          type: string
          example: admin@gmail.com
          description: O número máximo de caracteres é de 256
          minLength: 15
          maxLength: 256
        senha:
          type: string
          example: admin123
          description: O número máximo de caracteres é de 70
          minLength: 6
          maxLength: 70
    
    Bebida:
      required:
        - nome
        - litragem
        - descricao
        - id_categoria
        - id_marca
        - id_sabor
      type: object
      properties:
        nome:
          type: string
          description: O número máximo de caracteres é de 120
          minLength: 1
          maxLength: 120
        litragem:
          type: string
          description: O número máximo de caracteres é de 25
          minLength: 1
          maxLength: 25
        descricao:
          type: string
          description: O número máximo de caracteres é ilimitado
          minLength: 1
        id_categoria:
          type: integer
          example: 1
          minimum: 1
        id_marca:
          type: integer
          example: 3
          minimum: 1
        id_sabor:
          type: integer
          example: 2
          minimum: 1
        caracteristica:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
            example:
              - id: 1
              - id: 2
        foto_embalagem:
          type: array
          items:
            type: object
            properties:
              foto:
                type: string
              id_tipo_embalagem:
                type: integer
              valor:
                type: number
                format: double
            example:
              - id_foto: 1
                id_tipo_embalagem: 1
                valor: 3.50
              - id_foto: 2
                id_tipo_embalagem: 2
                valor: 7.00

    Categoria:
      required:
        - nome_categoria
      type: object
      properties:
        nome_categoria:
          type: string
          example: Refrigerante
          description: O número máximo de caracteres é de 30
          minLength: 1
          maxLength: 30
    
    Marca:
      required:
        - nome_marca
      type: object
      properties:
        nome_marca:
          type: string
          example: Coca Cola
          description: O número máximo de caracteres é de 60
          minLength: 1
          maxLength: 60

    Sabor:
      required:
        - nome_sabor
      type: object
      properties:
        nome_sabor:
          type: string
          example: Cola
          description: O número máximo de caracteres é de 60
          minLength: 1
          maxLength: 60
    
    Caracteristica:
      required:
        - nome
      type: object
      properties:
        nome:
          type: string
          example: Com gás
          description: O número máximo de caracteres é de 25
          minLength: 1
          maxLength: 25
    
    TipoEmbalagem:
      required:
        - tipo_embalagem
      type: object
      properties:
        tipo_embalagem:
          type: string
          example: Lata
          description: O número máximo de caracteres é de 40
          minLength: 1
          maxLength: 40
    
    Foto:
      required:
        - foto
      type: object
      properties:
        foto:
          type: string
          example: url da foto
          description: O número máximo de caracteres é de 200
          minLength: 1
          maxLength: 200

    # SCHEMAS PARA OS GETS (RELAÇÕES)
    UsuarioGet:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: Admin
          description: O número máximo de caracteres é de 30
          minLength: 4
          maxLength: 30
        email:
          type: string
          example: admin@gmail.com
          description: O número máximo de caracteres é de 256
          minLength: 15
          maxLength: 256
        jwt:
          type: string
          maxLength: 255
    
    BebidaGet:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: Coca Cola lata 350ML
          description: O número máximo de caracteres é de 120
        litragem:
          type: string
          example: 350ML
          description: O número máximo de caracteres é de 25
        descricao:
          type: string
          description: O número máximo de caracteres é ilimitado
        categoria:
          type: array
          items:
            $ref: '#/components/schemas/CategoriaGet'
        marca:
          type: array
          items:
            $ref: '#/components/schemas/MarcaGet'
        sabor:
          type: array
          items:
            $ref: '#/components/schemas/SaborGet'
        caracteristica:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              nome:
                type: string
          example:
            - id: 1
              nome: Com gás
            - id: 2
              nome: Sem álcool
        foto_embalagem:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              foto:
                type: string
              tipo_embalagem:
                type: string
              valor:
                type: number
                format: double
            example:
              - id: 1
                foto: coca_lata.png
                tipo_embalagem: Lata
                valor: 4.50
              - id: 2
                foto: coquinha.png
                tipo_embalagem: Garrafa
                valor: 3.00
    
    CategoriaGet:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome_categoria:
          type: string
          example: Refrigerante
          description: O número máximo de caracteres é de 30

    MarcaGet:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome_marca:
          type: string
          example: Coca Cola
          description: O número máximo de caracteres é de 60
    
    SaborGet:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome_sabor:
          type: string
          example: Cola
          description: O número máximo de caracteres é de 60

    CaracteristicaGet:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: Com gás
          description: O número máximo de caracteres é de 25

    TipoEmbalagemGet:
      type: object
      properties:
        id:
          type: integer
          example: 1
        tipo_embalagem:
          type: string
          example: Lata
          description: O número máximo de caracteres é de 40
      
    FotoGet:
      required:
        - foto
      type: object
      properties:
        id:
          type: integer
          example: 1
        foto:
          type: string
          example: url da foto
          description: O número máximo de caracteres é de 200
          items:
            $ref: '#/components/schemas/BebidaGet'

    # Login Usuário
    UsuarioLogin:
      required:
        - email
        - senha
      type: object
      properties:
        email:
          type: string
          example: admin@gmail.com
          description: O número máximo de caracteres é de 256
          minLength: 15
          maxLength: 256
        senha:
          type: string
          example: admin123
          description: O número máximo de caracteres é de 70
          minLength: 6
          maxLength: 70

  requestBodies: 
    Usuario:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Usuario'
    Bebida:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Bebida'
    
    Categoria:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Categoria'
    
    Marca:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Marca'
    
    Sabor:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Sabor'
    
    Caracteristica:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Caracteristica'
    
    TipoEmbalagem:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TipoEmbalagem'
    
    Foto:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Foto'

    # GETS
    UsuarioGet:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UsuarioGet'

    BebidaGet:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BebidaGet'
    
    CategoriaGet:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CategoriaGet'
    
    MarcaGet:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MarcaGet'
    
    SaborGet:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SaborGet'
    
    CaracteristicaGet:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CaracteristicaGet'
    
    TipoEmbalagemGet:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TipoEmbalagemGet'
    
    FotoGet:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FotoGet'

    #Login Usuário
    UsuarioLogin:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UsuarioLogin'